server:
  port: 8080

spring:
  application:
    name: rococo-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:9000'

grpc:
  client:
    userdata:
      address: 'static://localhost:8092'
      negotiation-type: PLAINTEXT
    geo:
      address: 'static://localhost:8094'
      negotiation-type: PLAINTEXT
    artist:
      address: 'static://localhost:8096'
      negotiation-type: PLAINTEXT
    museum:
      address: 'static://localhost:8098'
      negotiation-type: PLAINTEXT
    painting:
      address: 'static://localhost:8100'
      negotiation-type: PLAINTEXT

logging:
  level:
    root: INFO
    io.efremov.rococo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

rococo-front:
  base-uri: 'http://localhost:3000'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://rococo-auth:9000'

grpc:
  client:
    userdata:
      address: 'static://rococo-userdata:8092'
      negotiation-type: PLAINTEXT
    geo:
      address: 'static://rococo-geo:8094'
      negotiation-type: PLAINTEXT
    artist:
      address: 'static://rococo-artist:8096'
      negotiation-type: PLAINTEXT
    museum:
      address: 'static://rococo-museum:8098'
      negotiation-type: PLAINTEXT
    painting:
      address: 'static://rococo-painting:8100'
      negotiation-type: PLAINTEXT

rococo-front:
  base-uri: 'http://rococo-client'
