services:

  postgres:
    image: postgres:15.1
    container_name: rococo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_MULTIPLE_DATABASES: rococo_auth,rococo_gateway
      TZ: GMT+3
      PGTZ: GMT+3
    command: postgres
      -c max_prepared_transactions=100
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres-data:
